version: "3.7"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - FLASK_APP=flask_app/app.py
      - FLASK_RUN_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, utility]
